#!/bin/sh

set -e
set -x
if test -f Makefile; then
  make distclean
fi

# create a m4 directory if not already present
test -d m4 || mkdir m4

rm -rf *~ *.cache *.m4 config.guess config.log \
	config.status config.sub depcomp ltmain.sh
autoreconf --verbose --install --force
