#include <stdio.h>
#include <libp11.h>

#define PKCS11_LIB "/usr/lib/opensc-pkcs11.so"

int main(int argc, char *argv[])
{
	PKCS11_CTX *ctx;
	PKCS11_SLOT *slot;
	unsigned char random[10];
	int rc = 0, i, len;

	ctx = PKCS11_CTX_new();

	/* load pkcs #11 module */
	rc = PKCS11_CTX_load(ctx, PKCS11_LIB);
	if (rc) {
		fprintf(stderr, "loading pkcs11 engine failed: %s\n",
			ERR_reason_error_string(ERR_get_error()));
		rc = 1;
		goto nolib;
	}

	/* get first slot with a token */
	slot = PKCS11_find_token(ctx);
	if (!slot || !slot->token) {
		fprintf(stderr, "no token available\n");
		rc = 2;
		goto noslot;
	}
	printf("Slot manufacturer......: %s\n", slot->manufacturer);
	printf("Slot description.......: %s\n", slot->description);
	printf("Slot token label.......: %s\n", slot->token->label);
	printf("Slot token manufacturer: %s\n", slot->token->manufacturer);
	printf("Slot token model.......: %s\n", slot->token->model);
	printf("Slot token serialnr....: %s\n", slot->token->serialnr);

	/* get 10 random bytes */
	len = sizeof(random);
	rc = PKCS11_generate_random(slot, random, len);
	if (rc < 0) {
		fprintf(stderr, "generate_random failed: %s\n",
			ERR_reason_error_string(ERR_get_error()));
		rc = 3;
		goto norandom;
	}

	printf("\nRandom numbers generated by the token: ");
	for (i=0; i<len; i++)
		printf("%02X ", random[i]);
	printf("\n");

	rc = 0;
norandom:
noslot:
	PKCS11_CTX_unload(ctx);

nolib:
	PKCS11_CTX_free(ctx);
	return rc;
}

