name: Coverity Scan

on:
  push:
  pull_request:

jobs:
  coverity:
    runs-on: ubuntu-latest
    env:
      token: ${{secrets.COVERITY_SCAN_TOKEN}}
    steps:
    - uses: actions/checkout@v4
      if: env.token
    - name: Get ready for scanning
      if: env.token
      run: |
        sudo apt-get install -y libssl-dev opensc softhsm2
        autoreconf --verbose --install --force
        ./configure
    - uses: vapier/coverity-scan-action@v1
      if: env.token
      with:
        email: 'viktor.tarasov@gmail.com'
        token: ${{secrets.COVERITY_SCAN_TOKEN}}
        command: make
